language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy3"
  - "nightly"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.8.2
    - python: "2.6"
      env: DJANGO_VERSION=1.7.8
    - python: "3.2"
      env: DJANGO_VERSION=1.3.7
    - python: "3.2"
      env: DJANGO_VERSION=1.4.20
    - python: "3.3"
      env: DJANGO_VERSION=1.3.7
    - python: "3.3"
      env: DJANGO_VERSION=1.4.20
    - python: "3.4"
      env: DJANGO_VERSION=1.3.7
    - python: "3.4"
      env: DJANGO_VERSION=1.4.20
    - python: "pypy3"
      env: DJANGO_VERSION=1.3.7
    - python: "pypy3"
      env: DJANGO_VERSION=1.4.20
install:
  - pip install -q django==$DJANGO_VERSION
script: python tests.py
notifications:
  email: false