language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - sudo python setup.py install -f
    - pip install -r requirements.txt
script: python tests.py
notifications:
    email: false