language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy3"
    - "nightly"
env:
    - DJANGO_VERSION=1.3.7
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.2
install:
    - pip install -q django==$DJANGO_VERSION --use-mirrors
script: python tests.py
notifications:
    email: false